name: e2e-smoke-api

on:
  push:

jobs:
  e2e-smoke:
    if: "!contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    runs-on: ubuntu-latest
    env:
      DEBUG: currents:*

    services:
      director:
        image: agoldis/sorry-cypress-director
        ports:
          - 1234:1234

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install alternative cypress binaries
        run: CYPRESS_DOWNLOAD_MIRROR=https://cy-cdn.currents.dev npx cypress install --force

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Link monorepo packages
        run: npm install

      - name: Run Cypress with cypress-cloud CJS
        working-directory: ./examples/webapp
        env:
          CURRENTS_RECORD_KEY: "any"
          CURRENTS_API_URL: http://localhost:1234
        run: |
          npm run cypress:script

      - name: Run Cypress with cypress-cloud TS
        working-directory: ./examples/webapp
        env:
          CURRENTS_RECORD_KEY: "any"
          CURRENTS_API_URL: http://localhost:1234
        run: |
          npm run cypress:script:ts

      - name: Run Cypress with cypress-cloud ESM
        working-directory: ./examples/webapp
        env:
          CURRENTS_RECORD_KEY: "any"
          CURRENTS_API_URL: http://localhost:1234
        run: |
          npm run cypress:script:esm
