name: e2e-monorepo

on:
  push:

jobs:
  e2e-monorepo:
    if: "!contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    runs-on: ubuntu-latest
    env:
      DEBUG: currents:*

    services:
      director:
        image: agoldis/sorry-cypress-director
        ports:
          - 1234:1234

    strategy:
      matrix:
        node-version: ["18"]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Link monorepo packages
        run: npm install

      - name: Run from a monorepo
        working-directory: ./e2e/monorepo
        env:
          CURRENTS_API_URL: http://localhost:1234
        run: >
          npx cypress-cloud run
          --record
          --parallel
          --key some-key
          --browser chrome
          --tag smoke,linux
          -P ./packages/some
          --spec "./cypress/e2e/*.spec.js"
          --ci-build-id "${{ github.repository }}-${{ github.run_id }}-${{ github.run_attempt}}"
